# -*- Python -*-

java_binary(
    name = "cli",
    srcs = ["fr/fbauzac/TimeCompileCli.java"],
    deps = [
        "//lib:time-compile",
        "@jopt//jar",
    ],
    main_class = "fr.fbauzac.TimeCompileCli",
)
